i1<-subset(diabetic_data,insulin=="Up")
i2<-subset(diabetic_data,insulin=="Down")
i3<-subset(diabetic_data,insulin=="Steady")
i4<-subset(diabetic_data,insulin=="No")
x<-c(nrow(i1),nrow(i2),nrow(i3),nrow(i4))
label<-c("Up", "Down", "Steady", "No")
png(file="insulin.png")
pie3D(x,labels=label,explode=0.1,main="Analysis based on Adminstration of Insulin")
dev.off()
