i1<-subset(diabetic_data,metformin="Steady")
i2<-subset(diabetic_data,glimepiride="Steady")
i3<-subset(diabetic_data,glipizide="Steady")
i1<-subset(diabetic_data,metformin=="Steady")
i2<-subset(diabetic_data,glimepiride=="Steady")
i3<-subset(diabetic_data,glipizide=="Steady")
i4<-subset(diabetic_data,glyburide=="Steady")
i5<-subset(diabetic_data,acarbose=="Steady")
x<-c(nrow(i1),nrow(i2),nrow(i3),nrow(i4),nrow(i5))
piepercent<- round(100*x/sum(x),1)
png(file="medicine_final.png")
pie(x,labels=piepercent,main="Analysis based on Administration of Medication",col=rainbow(length(x)))
legend("topright",c("Metformin", "Glimepiride","Glipizide", "Glyburide", "Acarbose"),cex=0.8,fill=rainbow(length(x)))
dev.off()
