r1<- subset(diabetic_data, race=="Caucasian")
r2<- subset(diabetic_data, race=="AfricanAmerican")
r3<- subset(diabetic_data, race=="Asian")
r4<- subset(diabetic_data, race=="Hispanic")
r5<- subset(diabetic_data, race=="Other")
x<- c(nrow(r1),nrow(r2),nrow(r3),nrow(r4),nrow(r5))
label<- c("Caucasian","African American","Asian","Hispanic","Other")
library(plotrix)
piepercent<- round(100*x/sum(x),1)
png(file="race_final.png")
pie(x,labels=piepercent,main="Analysis based on Race",col=rainbow(length(x)))
legend("topright",c("Caucasian","AfricanAmerican","Asian","Hispanic","Others"),cex=0.8,fill=rainbow(length(x)))
dev.off()
